name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create .env
        run: |
          echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
          echo "NEXT_PUBLIC_API_HOST=${{ secrets.NEXT_PUBLIC_API_HOST }}" >> .env
          echo "NEXT_PUBLIC_ASSETS_HOST=${{ secrets.NEXT_PUBLIC_ASSETS_HOST }}" >> .env
          echo "NEXT_PUBLIC_GITHUB_URL=${{ secrets.NEXT_PUBLIC_GITHUB_URL }}" >> .env
          echo "NEXT_PUBLIC_DISCORD_URL=${{ secrets.NEXT_PUBLIC_DISCORD_URL }}" >> .env
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          IMAGE=ghcr.io/${{ github.repository }}:$VERSION
          docker build -t $IMAGE .
          docker push $IMAGE

